name: mamba-dev
channels:
  - conda-forge
  - wolfv
dependencies:
  - sel(unix): cxx-compiler
  - sel(win): vs2022_win-64
  - cmake
  - ninja
  - nlohmann_json
  - libsolv >=0.7.18
  - libarchive
  - libsodium
  - libcurl 7.82.0 *_0
  - gtest
  - gmock
  - cpp-expected
  - reproc-cpp
  - yaml-cpp
  - termcolor-cpp
  - cli11 >=2.2
  - spdlog
  - pybind11
  - pytest
  - conda
  - sel(win): winreg
