name: linter

on:
  push:
   branches:
     - master
  pull_request:
    branches:
     - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      shell: pwsh
      run: |
        python -m pip install pre-commit
    - name: Run all linters
      shell: pwsh
      run: |
        pre-commit run --all-files
